# This is a basic workflow to help you get started with Actions

name: Conventional Changelog Action
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ release-1.15 ]
  pull_request:
    branches: [ release-1.15 ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it   
      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v2
        with:
          github-token: ${{ secrets.github_token }}
          git-message: Updated Changelog
